import Vue from 'vue'

import './styles/quasar.styl'
import '@quasar/extras/material-icons/material-icons.css'
import {
  QAvatar,
  QAjaxBar,
  QCard,
  QCardSection,
  QCardActions,
  QBtn,
  QBadge,
  QDrawer,
  QForm,
  QHeader,
  QIcon,
  QImg,
  QInput,
  QItem,
  QItemSection,
  QItemLabel,
  QLayout,
  QList,
  QPage,
  QPageContainer,
  QRating,
  QRouteTab,
  QSelect,
  QSeparator,
  QSpinner,
  QTab,
  QTabs,
  QTime,
  QToolbar,
  QToolbarTitle,
  Quasar,

  // for spinner

  QSpinnerAudio,
  QSpinnerBall,
  QSpinnerBars,
  QSpinnerComment,
  QSpinnerCube,
  QSpinnerDots,
  QSpinnerFacebook,
  QSpinnerGears,
  QSpinnerGrid,
  QSpinnerHearts,
  QSpinnerHourglass,
  QSpinnerInfinity,
  QSpinnerIos,
  QSpinnerOval,
  QSpinnerPie,
  QSpinnerPuff,
  QSpinnerRadio,
  QSpinnerRings,
  QSpinnerTail,
  QInnerLoading
} from 'quasar'

Vue.use(Quasar, {
  config: {},
  components: {
    QAvatar,
    QAjaxBar,
    QBtn,
    QBadge,
    QCard,
    QCardSection,
    QCardActions,
    QDrawer,
    QForm,
    QHeader,
    QIcon,
    QImg,
    QInput,
    QItem,
    QItemSection,
    QItemLabel,
    QLayout,
    QList,
    QPage,
    QPageContainer,
    QRating,
    QRouteTab,
    QSelect,
    QSeparator,
    QSpinner,
    QTab,
    QTabs,
    QTime,
    QToolbar,
    QToolbarTitle,

    // for spinner

    QSpinnerAudio,
    QSpinnerBall,
    QSpinnerBars,
    QSpinnerComment,
    QSpinnerCube,
    QSpinnerDots,
    QSpinnerFacebook,
    QSpinnerGears,
    QSpinnerGrid,
    QSpinnerHearts,
    QSpinnerHourglass,
    QSpinnerInfinity,
    QSpinnerIos,
    QSpinnerOval,
    QSpinnerPie,
    QSpinnerPuff,
    QSpinnerRadio,
    QSpinnerRings,
    QSpinnerTail,
    QInnerLoading
  },
  directives: {
  },
  plugins: {
  }
 })
